server:
  port: 8080

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe  # Oracle ì ‘ì† URL
    username: c##gym                    # ğŸ‘‰ Oracle ì‚¬ìš©ì ê³„ì •
    password: 1234                    # ğŸ‘‰ Oracle ì‚¬ìš©ì ë¹„ë°€ë²ˆí˜¸
    driver-class-name: oracle.jdbc.OracleDriver

  devtools:
    restart:
      enabled: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.project.gym.domain
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com.project.gym: debug
    org.mybatis: debug
